version: "3.8"

services:
  server:
    build: .
    container_name: jp-nuxt
    restart: always
    ports:
      - "${SERVER_PORT}:3000"
    env_file:
      - ./.env
    volumes:
      - "./data:/app/data"
