name: ci

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Run Tests
        run: npm run test:unit

  e2e-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.13.2-chrome97-ff96
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          config-file: ./cypress.config.ts
          build: npm run build
          start: npm run start

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

  build-image:
    name: Build and push docker image
    if: github.ref_name == 'master'
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: tch1b0/jp-nuxt:latest
